spring:
  application:
    name: bus
#    配置rabbitmq主机
  rabbitmq:
    host: localhost
#    访问端口
    port: 5672
#    安装rabbitmq时配置的用户名
    username: guest
#    安装RabbitMQ时配置的密码
    password: guest

server:
  port: 9020